import Foundation

// MARK: - DailyTrajectory

/// A complete daily trajectory containing all time blocks for one day.
///
/// Generated by ``TrajectoryService`` based on the user's chronotype and sleep schedule.
/// The `blocks` array is sorted chronologically and covers the full day from wake to sleep.
struct DailyTrajectory: Sendable {
    /// The date this trajectory is for.
    let date: Date
    /// The user's chronotype used to generate this trajectory.
    let chronotype: Chronotype
    /// The user's wake time for this day.
    let wakeTime: Date
    /// The user's target sleep time for this day.
    let sleepTime: Date
    /// All trajectory blocks for the day, sorted by start time.
    let blocks: [TrajectoryBlock]
    /// The confidence level based on available sleep data.
    let confidence: ConfidenceLevel
}
